#!/bin/bash
fs=(
bench_sum_omptarget_loop_
)
for r in 1 4 16 64 256 1024;do
		fs+=(bench_sum_cuda_rbuf${r}_)
done
for r in 1 4 16 64 256 1024;do
	for m in 32 64 128 256 512 1024;do
		fs+=(bench_sum_omptarget_rbuf${r}_team${m}_)
	done
done

if (($#==0));then
	for ((i=0;i<${#fs[@]};++i));do
		echo $i "${fs[i]}" $(ls "exe/${fs[i]}"*/exe|wc -l)
	done
else
	while (($#>0));do
		i=$1
		shift
		((i>=${#fs[@]})) && continue
		echo $i "${fs[i]}" $(ls "exe/${fs[i]}"*/exe|wc -l)
		f="${fs[i]}"
		for b in "exe/$f"*/exe;do
			o="${b%/exe}"
			o="${o#exe/}"
			if [[ ! -s bench_out/$o ]];then
				echo $o
				./"$b" >& "bench_out/$o"
			fi
		done
	done
fi
